// permissionsRouter
const ADD_ROUTER = `ADD_ROUTER`;
const GENERATE_ROUTES = `GENERATE_ROUTES`;
// app
const SLIDE_BAR_COLLAPSE_CHANGE = `SLIDE_BAR_COLLAPSE_CHANGE`;
// tagsView
const ADD_ROUTE = `ADD_ROUTE`;
const DEL_ROUTE = `DEL_ROUTE`;
const DEL_OTHER_ROUTE = `DEL_OTHER_ROUTE`;
// userInfo
const ADD_ROLES = `ADD_ROLES`;
const ADD_USER_INFO = `ADD_USER_INFO`;
const CLEAR_USER_INFO = `CLEAR_USER_INFO`;
const REQ_GET_USER_INFO = `REQ_GET_USER_INFO`;
export {
    ADD_ROUTER,
    GENERATE_ROUTES,
    SLIDE_BAR_COLLAPSE_CHANGE,
    ADD_ROUTE,
    DEL_ROUTE,
    DEL_OTHER_ROUTE,
    ADD_ROLES,
    ADD_USER_INFO,
    CLEAR_USER_INFO,
    REQ_GET_USER_INFO
};
